### PR TITLE
Update java_main.yml

### PR DESCRIPTION
**Pull request by slangeberg**
I really don't know what i'm doing...

Hi there, @celkins, I can't figure out how to deploy a fat jar for the life of me, to Pivotal.io / cloud foundry. Any help appreciated! Am I able to stuff my drop wizard server config .yml file in this build pack, and point to it, or something? I have yet to get one of these things running. :) Scott

### CODE REVIEW

**Comment by slangeberg** [comment]
Here's what i used in my last push attempt. Perhaps all is well, and I'm getting some suitable config defaults? I'm using some lazy template to set things up, and when you hit my app, you'll get a 503, which might make Pivotal unhappy. Looks like Jersey wants me to configure my resources. However, it would be nice to know if / where I need to configure the Dropwizard app.

> cf push lazydrops -p build/distributions/lazydrops-0.1-shadow.jar -b https://github.com/slangeberg/dropwizard-buildpack

Thanks again!

**Comment by celkins** [comment]
There are at least a couple problems with your config file in CF.
1. CF allocates an HTTP port dynamically, and you need to pass that to your Dropwizard application at startup.
2. You only get one HTTP port per CF application, so attempting to create an admin listener on a secondary port will fail (perhaps silently).

In its current form, this buildpack effectively runs a Dropwizard application as follows:

```
java -Ddw.server.type=simple -Ddw.server.applicationContextPath=/ -Ddw.server.connector.type=http -Ddw.server.connector.port=$PORT -jar myapp.jar server
```

where `$PORT` is initialized by the buildpack.

**Comment by ptrecenti** [comment]
Hi @celkins, 

Is there any sample project or manifest.yml configuration to use this buildpack ?

**Comment by celkins** [comment]
@ptrecenti Yes, my `dropwizard-example` project includes one:
https://github.com/celkins/dropwizard-example/blob/master/manifest.yml

**Comment by stwomack** [comment]
@celkins I'm posting this beacuse I cannot create an issue.

When I use this, I fail with "ERR Application can be run by more than one container: Java Main, Spring Boot CLI"

I'm including the contents of my manifest.yml file. Note that I've tried this with and without the 'command' option populated. Both fail with the same error. I tried it with it because I want to use my dropwizard config. Your example project doesn't seem to have a config file. 

applications:
- name: item-master-api-dropwizard
  memory: 512M
  path: target/item-master-api-dropwizard-1.0-SNAPSHOT.jar
  buildpack: https://github.com/celkins/dropwizard-buildpack.git
  # command: java -jar target/item-master-api-dropwizard-1.0-SNAPSHOT.jar server item-master.yml"

**Comment by celkins** [comment]
@stwomack I don't think the current Java build pack supports the CF `manifest` command attribute; this older fork of it certainly doesn't.

At present the only way I know of to pass additional arguments to the start command, including specifying a configuration file, is by extending the build pack as I've done [here](https://github.com/celkins/dropwizard-buildpack/blob/976287e9c87aa8e56c9e14becbd32c6fcec441bd/config/java_main.yml#L2).

**Pull request closed without merging**
